# Generated by Django 4.0.2 on 2022-02-10 15:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre propietario')),
                ('owner_type', models.SmallIntegerField(choices=[(0, 'Persona'), (1, 'Empresa')])),
                ('identification', models.CharField(max_length=50, unique=True, verbose_name='Identificación')),
            ],
            options={
                'verbose_name': 'Propietario',
                'verbose_name_plural': 'Propietarios',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=200, verbose_name='Identificación')),
                ('estate_type', models.SmallIntegerField(choices=[(0, 'Urbano'), (1, 'Rural')])),
                ('cadastral_certificate', models.CharField(max_length=50, unique=True, verbose_name='Cédula catastral')),
                ('estate_registration', models.CharField(max_length=50, unique=True, verbose_name='Matricula inmobiliaria')),
                ('owners', models.ManyToManyField(blank=True, null=True, related_name='estates', to='properties.Owner')),
            ],
            options={
                'verbose_name': 'Predio',
                'verbose_name_plural': 'Predios',
                'ordering': ['created'],
            },
        ),
    ]
